name: Publish

on:
  push:
    tags:
      - '*'
      
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2        
      with:
          fetch-depth: 0
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: '6.x'
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.11
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.11
    - name: Install Dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish --configuration Release /p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }} /p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }}
    - name: Pack
      run: 7z a LiveSense-${{ steps.gitversion.outputs.semVer }}.zip .\LiveSense\bin\Release\win-x64\publish\*
    - name: Create Release
      id: create-release
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        fail_on_unmatched_files: true
        name: LiveSense v${{ steps.gitversion.outputs.semVer }}
        files: LiveSense-${{ steps.gitversion.outputs.semVer }}.zip
