name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2        
      with:
          fetch-depth: 0
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Install Dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish --configuration Release /p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }} /p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }}
    - name: Pack
      run: 7z a LiveSense-${{ steps.gitversion.outputs.semVer }}.zip .\LiveSense\bin\Release\win-x64\publish\*
    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: LiveSense v${{ steps.gitversion.outputs.semVer }}
        draft: false
        prerelease: false
    - name: Upload Release Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_name: LiveSense-${{ steps.gitversion.outputs.semVer }}.zip
        asset_path: ./LiveSense-${{ steps.gitversion.outputs.semVer }}.zip
        asset_content_type: application/zip
